### ISSUE TITLE
pnpm run dev

### ISSUE THREAD

**Issue by joshyates1980** [sporeprotocol/spore-demo#66]
README.md was very clear about clone the repository.
After I successfully close, I execute the command **pnpm run dev**

`PS C:\VSCode\spore-demo> pnpm run dev                                 

> spore-demo@0.1.0 dev C:\VSCode\spore-demo
> next dev

  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000

 ✓ Ready in 1571ms
 ○ Compiling / ...
 ✓ Compiled / in 3.3s (2544 modules)
 ⨯ TypeError: Cannot read properties of undefined (reading 'http')
    at file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/providers/public.js:6:31
    at configureChains (file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:29:25)
    at new MetaMaskConnector (webpack-internal:///./src/connectors/metamask.ts:29:117)
    at eval (webpack-internal:///./src/pages/_app.tsx:137:9) {
  page: '/'
}
 ✓ Compiled /_error in 132ms (2528 modules)
TypeError: Cannot read properties of undefined (reading 'http')
    at file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/providers/public.js:6:31
    at configureChains (file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:29:25)
    at new MetaMaskConnector (webpack-internal:///./src/connectors/metamask.ts:29:117)
    at eval (webpack-internal:///./src/pages/_app.tsx:137:9)
 ✓ Compiled /not-found in 977ms (2890 modules)
 ⨯ TypeError: Cannot read properties of undefined (reading 'http')
    at file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/providers/public.js:6:31
    at configureChains (file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:29:25)
    at new MetaMaskConnector (webpack-internal:///./src/connectors/metamask.ts:29:117)
    at eval (webpack-internal:///./src/pages/_app.tsx:137:9) {
  page: '/'
}
 ⨯ TypeError: Cannot read properties of undefined (reading 'http')
    at file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/providers/public.js:6:31
    at configureChains (file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:29:25)
    at new MetaMaskConnector (webpack-internal:///./src/connectors/metamask.ts:29:117)
    at eval (webpack-internal:///./src/pages/_app.tsx:137:9) {
  page: '/'
}
TypeError: Cannot read properties of undefined (reading 'http')
    at file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/providers/public.js:6:31
    at configureChains (file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:29:25)
    at new MetaMaskConnector (webpack-internal:///./src/connectors/metamask.ts:29:117)
    at eval (webpack-internal:///./src/pages/_app.tsx:137:9) {
  page: '/'
}
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ⨯ TypeError: Cannot read properties of undefined (reading 'http')
    at file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/providers/public.js:6:31
    at configureChains (file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:29:25)
    at new MetaMaskConnector (webpack-internal:///./src/connectors/metamask.ts:29:117)
    at eval (webpack-internal:///./src/pages/_app.tsx:137:9) {
  page: '/'
}
TypeError: Cannot read properties of undefined (reading 'http')
    at file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/providers/public.js:6:31
    at configureChains (file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:29:25)
    at new MetaMaskConnector (webpack-internal:///./src/connectors/metamask.ts:29:117)
    at eval (webpack-internal:///./src/pages/_app.tsx:137:9) {
  page: '/'
}
 ⨯ TypeError: Cannot read properties of undefined (reading 'http')
    at file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/providers/public.js:6:31
    at configureChains (file:///C:/VSCode/spore-demo/node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:29:25)
    at new MetaMaskConnector (webpack-internal:///./src/connectors/metamask.ts:29:117)
    at eval (webpack-internal:///./src/pages/_app.tsx:137:9) {
  page: '/favicon.ico'
}
`

Google Chrome browser:

![image](https://github.com/sporeprotocol/spore-demo/assets/7255545/c740645e-3652-49aa-b6bf-6ca24b812cc8)

VS CODE:

![image](https://github.com/sporeprotocol/spore-demo/assets/7255545/4e39708a-fdbe-4874-8fff-995f01cd9344)

**Comment by ahonn** [comment]
Hi, thanks for your feedback.
This seems to be a version issue with either Node.js or PNPM. Can you please provide the versions you are currently using?

**Comment by joshyates1980** [comment]
@ahonn 
![image](https://github.com/sporeprotocol/spore-demo/assets/7255545/22fa308d-3e5f-44b5-bbca-07c8d75bf2d3)
